# %%


import os
# import sys
# import argparse
from dotenv import load_dotenv
import sqlite3
from dataclasses import dataclass
from typing import Callable, Any
import re

from langchain_openai import ChatOpenAI
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain.agents.middleware import before_agent, AgentState, wrap_tool_call
from langchain_core.messages import SystemMessage, AIMessage, HumanMessage, ToolMessage
from langgraph.runtime import Runtime
from langgraph.graph import MessagesState, START, END, StateGraph
from langgraph.checkpoint.memory import InMemorySaver 
from langchain.tools.tool_node import ToolCallRequest
from langgraph.types import Command

from deepagents import create_deep_agent
from deepagents.backends import FilesystemBackend

from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())


# %%


@dataclass
class Context:
    CustomerID: str

base_dir = os.path.dirname(os.path.abspath(__file__))

db_path = os.path.join(base_dir, "./db/northwind.db")
db = SQLDatabase.from_uri(
    f"sqlite:///{db_path}",
    sample_rows_in_table_info = 3
)

model = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
)

toolkit = SQLDatabaseToolkit(db=db, llm=model)
sql_tools = toolkit.get_tools()

@before_agent
def ingest_customerID(state: AgentState, runtime: Runtime) -> dict[str, Any] | None:
    return {
        "messages": [SystemMessage(f"customer ID is {runtime.context.CustomerID}.")]
    }

def _is_customer_scoped(sql: str, customer_id: str) -> bool:

    """
    Returns True if SQL contains a predicate that scopes to exactly:
      CustomerID = '<customer_id>'  (or with double quotes)
    
    Args:
        sql: sql query generated by LLM
        customer_id: customer_id required for SQL scope
    """
    
    if not sql or not customer_id:
        return False

    s = " ".join(sql.strip().split())

    pattern = rf"""
        \bCustomerID\b
        \s*=\s*
        (['"])
        {re.escape(customer_id)}
        \1
    """
    return re.search(pattern, s, flags=re.IGNORECASE | re.VERBOSE) is not None


@wrap_tool_call
def customer_scope_guard(
    request: ToolCallRequest,
    handler: Callable[[ToolCallRequest], ToolMessage | Command],
) -> ToolMessage | Command:
    
    """
    Blocks QuerySQLDatabaseTool unless SQL includes:
        CustomerID = runtime.context.CustomerID
    """

    tool_name = request.tool_call["name"]
    args = request.tool_call["args"]

    # Only guard QuerySQLDatabaseTool
    if tool_name not in ("QuerySQLDatabaseTool"):
        return handler(request)

    # Extract SQL input (tool schema typically uses {"query": "..."} )
    sql = args.get['query']
    if not sql:
        raise ValueError("Missing start_time or end_time for conflict check")

    # Pull CustomerID from runtime context
    runtime = request.runtime
    customer_id = None
    if runtime and getattr(runtime, "context", None):
        customer_id = getattr(runtime.context, "CustomerID", None)

    if not customer_id:
        return ToolResponse(
            messages=[
                ToolMessage(
                    tool_call_id=request.tool_call_id,
                    content=(
                        "Blocked: runtime.context.CustomerID is missing, so I cannot safely run SQL.\n"
                        "Please set runtime.context.CustomerID first."
                    ),
                )
            ]
        )

    if not _is_customer_scoped(sql, customer_id):
        return ToolResponse(
            messages=[
                ToolMessage(
                    tool_call_id=request.tool_call_id,
                    content=(
                        "Blocked: SQL must be scoped to a single customer.\n\n"
                        f"Required filter: CustomerID = '{customer_id}'\n\n"
                        "Please rewrite the SQL query to include that predicate."
                    ),
                )
            ]
        )

    # OK -> execute tool
    return handler(request)


# %%


sql_agent = create_deep_agent(
    model = model,                                  
    memory = ["./AGENTS.md"],                       
    skills = ["./skills/"],                         
    tools = sql_tools,                              
    subagents = [],                                 
    backend = FilesystemBackend(root_dir=base_dir),
    context_schema = Context,
    middleware = [ingest_customerID, customer_scope_guard],
)


# %%


config = {"configurable": {"thread_id": "1"}}
result = sql_agent.invoke(
    input = {"messages": [{"role": "user", "content": "List my recent 5 orders?"}]},
    context = Context(CustomerID="ALFKI"),
    config = config,
)

for i in result['messages']:
    i.pretty_print()


# %%